#!/usr/bin/env bash

# Lipstick build script.

echo "Building Lipstick on a Pig…"

# Helpers.
INSTALL="dist/install"

function write  { echo "${1}" >> "${INSTALL}"; }
function insert { cat "${1}" >> "${INSTALL}";  }

function embed {
  # Embed external file into bash variable in install script.
  # $1: path of file to embed
  # $2: name of variable to create

  write ""
  write "read -rd '' ${2} <<-EOF"
  insert "./src/${1}"
  write "EOF"
  write ""
  write "######################################################################"
}

scripts=()
fileNames=(
  "lipstick" 
  "lipstick-apps"
  "lipstick.service"
)

# Prepare distribution folder.
rm -rf ./dist
mkdir -p ./dist

# Start creating install script.
insert template/head.bash

embed lipstick "lipstick"
embed lipstick-apps "lipstickApps"
embed lipstick.service "lipstickService"

# Complete install script.
insert template/main.bash

echo 'Done.'
