#!/usr/bin/env bash

# Lipstick build script.

echo -n "🐷 Building Lipstick on a Pig…"

# Helpers.
INSTALL="dist/install"

function write  {
  # Append passed string ($1) to the install script.
  echo "${1}" >> "${INSTALL}"
}

function insert {
  # Append file at path ($1) to the install script without
  # altering it in any way.
  cat "${1}" >> "${INSTALL}"
}

function insertEscaped {
  # Append file at path ($1) to the install script,
  # making sure we escape dollar signs so as not
  # to have the code altered when the install script
  # runs.
  cat "${1}" | sed s/\\$/\\\\$/g >> "${INSTALL}"
}

function embed {
  # Embed external file into bash variable in install script.
  # $1: path of file to embed
  # $2: name of variable to create
  write ""
  write "read -rd '' ${2} <<-EOF"
  insertEscaped "./src/${1}"
  write "EOF"
  write ""
  write "######################################################################"
}

scripts=()
fileNames=(
  "lipstick" 
  "lipstick-apps"
  "lipstick.service"
)

# Prepare distribution folder.
rm -rf ./dist
mkdir -p ./dist

# Start creating install script.
insert template/head.bash

embed lipstick "lipstick"
embed lipstick-apps "lipstickApps"
embed lipstick.service "lipstickService"

# Complete install script.
insert template/main.bash

# Mark install script as executable.
chmod +x dist/install

echo ' 💄 Done.'
