#!/usr/bin/env bash

# Disables, stops, and uninstalls Lipstick.

# Use CONFIG as the configuration directory in app definitions.
# Adheres to freedesktop.org XDG Base Directory Specification
# https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
if test -z "${XDG_CONFIG_HOME}"; then
  CONFIG="${XDG_CONFIG_HOME}"
else
  CONFIG="${HOME}/.config"
fi

BIN="${HOME}/.local/bin"

"${BIN}/lipstick-disable"

rm -rf "${CONFIG}/lipstick"
rm "${CONFIG}/systemd/user/lipstick.service"
rm "${BIN}/lipstick-monitor"
rm "${BIN}/lipstick-update"
rm "${BIN}/lipstick-enable"
rm "${BIN}/lipstick-disable"
rm "${BIN}/lipstick-uninstall"
