#!/usr/bin/env bash

echo "Updating Lipstick on a Pig…"

if command -v wget &> /dev/null; then
  # Update using wget.
  wget -qO- https://codeberg.org/small-tech/lipstick/raw/branch/main/install | bash
else
  # wget does not exist, attempt to update using curl.
  if command -v curl &> /dev/null; then
    # Update using curl.
    curl -s https://codeberg.org/small-tech/lipstick/raw/branch/main/install | bash
  else
    echo "Error: could not find wget or curl to download the update."
    echo "Please install one of these apps and re-run lipstick-update."
    exit 1
  fi
fi

echo "Done."
