#!/usr/bin/env bash

################################################################################
#
# 🐷 Lipstick on a Pig
#
# 💄 Usage: lipstick <command>
#
# For list of commands, run lipstick help.
#
# For source code, documentation, etc., please see:
# https://codeberg.org/small-tech/lipstick
#
# Copyright © 2022-present Aral Balkan, Small Technology Foundation
# License: AGPL version 3.0.
#
################################################################################

VERSION="1.0"

# Binary and configuration path usage adheres to 
# freedesktop.org XDG Base Directory Specification
# https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
BINARY_HOME="${HOME}/.local/bin"

DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
LIPSTICK_DATA_HOME="${DATA_HOME}/lipstick"

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
SYSTEMD_USER_DIRECTORY="${CONFIG_HOME}/systemd/user"

RUNNING_PROGRAM_NAME="${0}"

function configure {
  # Import list of all apps (apps), including their configuration functions.
  source "${LIPSTICK_DATA_HOME}/lipstick-apps"

  # Find and initialise support for all supported apps installed on this system.
  installedApps=()

  for app in ${apps[@]};
  do
    appCommand="${app}Command"
    if command -v "${!appCommand}" &> /dev/null; then
      # App is installed.
      echo "  • Found app: ${app} (${!appCommand}), adding support for it"
      installedApps+=("${app}")
      "${app}Init"
    fi
  done

  # Save the list of installed apps.
  echo -e "#!/usr/bin/env bash\n\ninstalledApps=(${installedApps[@]})" > "${LIPSTICK_DATA_HOME}/installed-apps"
}


function monitor {
  # When system colour scheme changes, run sync script.
  gsettings monitor org.gnome.desktop.interface color-scheme \
    | xargs -L1 "${BINARY_HOME}/lipstick"
}


function sync {
  # Run all colour scheme updates for configured apps based on
  # the passed colour scheme ($1). Possible values are “default” for light and
  # anything else for dark.
  
  # Import list of all apps (apps), including their configuration functions,
  # as well as a list of the currently installed apps (installedApps) on this system.
  # (The latter is compiled by the lipstick-configure script run by the installer.)
  source "${LIPSTICK_DATA_HOME}/lipstick-apps"
  source "${LIPSTICK_DATA_HOME}/installed-apps"

  # Note: when called with the output of gsettings monitor, default and prefer-dark
  # are returned while when called with the output of gsettings get, you get
  # 'default' and 'prefer-dark' (with single quotes). So we remove the single quotes
  # here if they exist before checking.
  if [[ "${1//\'/}" = "default" ]]; then
    colourScheme="Light"
  else
    colourScheme="Dark"
  fi

  # Log the current mode to aid with troubleshooting.
  # Use journalctl --unit=lipstick.service to view the logs.
  echo "🐷 Switching to ${colourScheme} Mode."

  # Configure apps for the current colour scheme.
  for app in ${installedApps[@]};
  do
    appCommand="${app}Command"
    echo "💄 Setting ${colourScheme,,} colour scheme for ${app} (${!appCommand})"
    "${app}${colourScheme}"
  done
}


function showSmallHeader {
  echo "🐷 Lipstick on a Pig"
  echo ""
}


function status {
  # Show systemd service status.
  showSmallHeader
  systemctl status --user --no-pager lipstick
}


function logs {
  # Show systemd service logs.
  showSmallHeader
  journalctl --user --unit=lipstick --follow
}

function enableService {
  # Enable the Lipstick monitor to start on boot, start it up immediately,
  # and also run the sync command right away with the current colour scheme.
  sync `gsettings get org.gnome.desktop.interface color-scheme`
  systemctl --user enable lipstick.service 2>&1 1>/dev/null
  systemctl --user start lipstick.service 2>&1 1>/dev/null
}


function disableService {
  # Stop the Lipstick colour scheme change monitor service immediately and
  # disable it from starting at boot.
  systemctl --user stop lipstick.service 2>&1 1>/dev/null
  systemctl --user disable lipstick.service 2>&1 1>/dev/null
}


function update {
  # Update Lipstick on a Pig.
  echo -e "🐷 Updating Lipstick on a Pig…"

  uninstall 2>&1 1>/dev/null

  if command -v wget &> /dev/null; then
    # Update using wget.
    wget -qO- https://raw.githubusercontent.com/killeik/lipstick/refs/heads/main/dist/install| bash 2>&1 1>/dev/null
  else
    # As wget does not exist, attempt to update using curl.
    if command -v curl &> /dev/null; then
      # Update using curl.
      curl -s https://raw.githubusercontent.com/killeik/lipstick/refs/heads/main/dist/install | bash 2>&1 1>/dev/null
    else
      echo "Error: could not find wget or curl to download the update."
      echo "Please install one of these apps and re-run lipstick-update."
      exit 1
    fi
  fi

  echo "💄 Done."
}


function uninstall {
  # Uninstall Lipstick on a Pig.
  echo "🐷 Uninstalling Lipstick on a Pig…"

  disableService 2>&1 1>/dev/null

  rm -rf "${LIPSTICK_DATA_HOME}"
  rm "${CONFIG_HOME}/systemd/user/lipstick.service"
  rm "${BINARY_HOME}/lipstick"
  
  echo "💄 Done."
}


function showHelp {
  echo "🐷 Lipstick on a Pig version ${VERSION}"
  echo ""
  echo "💄 Usage: lipstick <command>"
  echo ""
  echo "Commands:"
  echo ""
  echo "configure: update config (e.g., after installing a new app)"
  echo "update   : update to latest version of Lipstick on a Pig."
  echo "status   : display status of systemd service"
  echo "logs     : display systemd service logs"
  echo "enable   : enable and start systemd service"
  echo "disable  : disable and stop systemd service"
  echo "uninstall: uninstall Lipstick on a Pig."
  echo ""
  echo "To access source code, file an issue, etc., please see:"
  echo "https://codeberg.org/small-tech/lipstick"
  echo ""
  echo "💕 Like this? Fund us!"
  echo "   https://small-tech.org/fund-us"
  echo ""
  echo "Copyright 2022-present Aral Balkan, Small Technology Foundation"
  echo "Released under AGPL version 3.0"
}

function main {
  # Are we being called by the colour scheme change monitoring service
  # with a sync request?
  if [[ "${1}" = "color-scheme:" ]]; then
    # Called by monitoring service. Run sync and exit.
    sync "${2}"
    exit
  fi

  # Parse command.

  case $1 in
    configure     ) configure      ;;
    monitor       ) monitor        ;;  # private; only used by systemd service.
    sync          ) sync "${2}"    ;;  # private; only used by systemd service.
    status        ) status         ;;
    logs          ) logs           ;;
    enable        ) enableService  ;;
    disable       ) disableService ;;
    update        ) update         ;;
    uninstall     ) uninstall      ;;
    *             ) showHelp       ;;
  esac
}

# Run main, passing in the arguments that were passed to the script.
main $@
