#!/usr/bin/env bash

# Lipstick

VERSION="1.0"

case $1 in
  configure     ) configure ;;
  monitor       ) monitor   ;;  # private; undocumented.
  sync          ) sync      ;;  # private; undocumented.
  enable        ) enable    ;;
  disable       ) disable   ;;
  update        ) update    ;;
  uninstall     ) uninstall ;;
  *             ) help      ;;
esac

# Use CONFIG as the configuration directory in app definitions.
# Adheres to freedesktop.org XDG Base Directory Specification
# https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
if test -z "${XDG_CONFIG_HOME}"; then
  CONFIG="${XDG_CONFIG_HOME}/lipstick"
else
  CONFIG="${HOME}/.config/lipstick"
fi
mkdir -p "${CONFIG}"


function configure {
  # Find and initialise support for all supported apps installed on this system.
  installedApps=()

  for app in ${lipstickApps[@]};
  do
    appCommand="${app}Command"
    if command -v "${!appCommand}" &> /dev/null; then
      # App is installed.
      echo "  - Found app: ${app}, adding support for it"
      installedApps+=(app)
      "${app}Init"
    fi
  done

  # Save the list of installed apps.
  echo "#!/usr/bin/env bash\n\ninstalledApps=(${installedApps[@]})" > "${CONFIG}/installed-apps"
}


function monitor {
  # When system colour scheme changes, run sync script.
  gsettings monitor org.gnome.desktop.interface color-scheme \
    | xargs -L1 bash -c "source ${HOME}/.local/bin/lipstick-sync"
}


function sync {
  # Import list of all apps (apps), including their configuration functions,
  # as well as a list of the currently installed apps (installedApps) on this system.
  # (The latter is compiled by the lipstick-configure script run by the installer.)
  source "${CONFIG}/lipstick-apps"
  source "${CONFIG}/installed-apps"

  if [[ "${1}" == "default" ]]; then
    colourScheme="Light"
  else
    colourScheme="Dark"
  fi

  # Log the current mode to aid with troubleshooting.
  # Use journalctl --unit=lipstick.service to view the logs.

  # Configure apps for the current colour scheme.
  for app in ${installedApps[@]};
  do
    "${app}${colourScheme}"
  done
}


function enable {
  # Enable the Lipstick monitor to start on boot, start it up immediately,
  # and also run the update command right away.

  "${HOME}/.local/bin/lipstick-update"
  systemctl --user enable lipstick.service
  systemctl --user start lipstick.service
}


function disable {
  # Stop the Lipstick colour scheme change monitor service immediately and
  # disable it from starting at boot.

  systemctl --user stop lipstick.service
  systemctl --user disable lipstick.service
}


function update {
  # Update Lipstick on a Pig.
  echo "Updating Lipstick on a Pig…"

  if command -v wget &> /dev/null; then
    # Update using wget.
    wget -qO- https://codeberg.org/small-tech/lipstick/raw/branch/main/install | bash
  else
    # wget does not exist, attempt to update using curl.
    if command -v curl &> /dev/null; then
      # Update using curl.
      curl -s https://codeberg.org/small-tech/lipstick/raw/branch/main/install | bash
    else
      echo "Error: could not find wget or curl to download the update."
      echo "Please install one of these apps and re-run lipstick-update."
      exit 1
    fi
  fi

  echo "Done."
}


function uninstall {
  "${BIN}/lipstick disable"

  rm -rf "${CONFIG}/lipstick"
  rm "${CONFIG}/systemd/user/lipstick.service"
  rm "${BIN}/lipstick"
}


function help {
  echo ""
  echo "🐷 Lipstick version ${VERSION}"
  echo ""
  echo "Usage: lipstick <command>"
  echo ""
  echo "Comands:"
  echo ""
  echo "configure: update config (e.g., after installing a new app)"
  echo "update   : update to latest version of Lipstick on a Pig."
  echo "enable   : enable and start the systemd service"
  echo "disable  : disable and stop the systemd service"
  echo "uninstall: uninstall Lipstick on a Pig."
  echo ""
  echo "Enjoy!"
  echo ""
  echo "💕 Like this? Fund us!"
  echo "   https://small-tech.org/fund-us"
  echo ""
  echo "Copyright 2022-present Aral Balkan, Small Technology Foundation"
  echo "Released under AGPL version 3.0"
  echo ""
}
