#!/usr/bin/env bash

# When system colour scheme changes, run sync script.
gsettings monitor org.gnome.desktop.interface color-scheme \
  | xargs -L1 bash -c "source ${HOME}/.local/bin/lipstick-sync"
