#!/usr/bin/env bash

# Stop the Lipstick colour scheme change monitor service immediately and
# disable it from starting at boot.

systemctl --user stop lipstick.service
systemctl --user disable lipstick.service
